# netlify.toml
[build]
  base = ""                                      # raíz del repo
  command = "pnpm install --prefer-offline && pnpm build"
  publish = "dist"                                # dist en raíz

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_PNPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200