# netlify.toml
[build]
  base = "src"
  command = "pnpm install --prefer-offline && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_PNPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200